# Generated by Django 5.1.3 on 2024-11-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_customer_user_seller_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('author_name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
