# Generated by Django 5.1.3 on 2024-11-27 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Customer_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='new_app.customer'),
            preserve_default=False,
        ),
    ]
